### ISSUE TITLE
DescribeDomainRecordInfoRequest应该已经获取不到IP了

### ISSUE THREAD

**Issue by lersh** [Mickyxing/aliyundns#1]
看阿里的帮助，https://help.aliyun.com/document_detail/29752.html?spm=5176.doc29754.6.141.sdnHKN
已经不返回value了，我猜测可能是觉得直接本地解析dns就能得到ip了也就无所谓在接口里返回了

**Comment by Mickyxing** [comment]
@lersh 你这个接口找错了，这个是返回域名信息的，我这个是修改域名解析记录的 https://help.aliyun.com/document_detail/29774.html?spm=5176.doc29752.6.163.f9gcDq

**Comment by lersh** [comment]
并没有错，你的代码里不是要对比新老ip是否一致吗？你在获取老ip时调用了aliyun.api.Dns20150109DescribeDomainRecordInfoRequest()来获取老的ip。
这个方法你试试看，应该不会返回value了

**Comment by Mickyxing** [comment]
@lersh  在获取老ip时我调用的是DescribeDomainRecordInfo这个接口地址是https://help.aliyun.com/document_detail/29777.html?spm=5176.doc29776.6.166.q7Wkjl 这个跟你说的DescribeDomainInfo这个是两个不同的接口

**Comment by lersh** [comment]
@Mickyxing  不好意思，我在第一行里打错了，实际上，我看的的确是https://help.aliyun.com/document_detail/29777.html?spm=5176.doc29776.6.166.q7Wkjl 这个DescribeDomainRecordInfo 接口，你可以试验下，我调用的时候，value字段一直都是返回空

**Comment by lersh** [comment]
不好意思，我又看了下，这个应该是alidns的c#版的bug，python版没问题
不知道如何联系aliyun的开发，alidns的c#版没有提交到github，想提bug都没地方

**Comment by Mickyxing** [comment]
@lersh 你登陆阿里云后提交个工单就行了，我上次刚开始不知道怎么找到RecordId 也是通过工单咨询才知道的

**Comment by lersh** [comment]
@Mickyxing 谢谢
